# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on: [workflow_dispatch]
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nuova

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
       repository: apache/dubbo
       path: './bar/dubbo'
      
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

 
    - name: Install dependencies
      run: 
        pip install -r requirements.txt
      

    - name: output
      run: | 
            cd /home/runner/work/Prova/Prova/bar/dubbo
            ls -a

 #         python3 runSZZ.py /home/runner/work/Prova/Prova/bar/dubbo dubbo java
  #        python3 commits_features.py https://github.com/apache/dubbo.git
    #      gzip -d dubbo-annotations.json.gz
    #      gzip -d dubbo-bugs.json.gz 
  #        python3 commit_selector.py
   #       python3 CreateCsv.py
  #        python3 CreateModel.py
    
        
        
    - name: Commit report
      run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "prova"
          git push 
   
