# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nuova

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        token: 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
    - name: Install dependencies
      run: 
        pip install -r requirements.txt
    - name: get id
      run: echo "GITHUB_SHA_SHORT=$(git log -n1 --format="%H")" >> $GITHUB_ENV
      

    - name: output
      run: python3 classificatori.py > testo.txt
      
      
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        file_pattern: '*.txt'

        
        
#    - name: Commit report
#      run: |
 #         git config --global user.name 'Luigi'
 #         git config --global user.email 'R-luigi99@users.noreply.github.com'
  #        git clone https://@github.com/R-luigi99/Prova.git
   #       git add testo.txt
     #     git commit -m "prova"
     #     git push
   
