# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nuova

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: 
        pip install -r requirements.txt
    - name: get id
      run: echo "GITHUB_SHA_SHORT=$(git log -n1 --format="%H")" >> $GITHUB_ENV
      

    - name: output
      run: python3 classificatori.py > testo.txt
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Your Name
        author_email: ricciuto99@gmail.com
        message: 'Your commit message'
        add: '*.txt'
   
